### ISSUE TITLE
Schema

### ISSUE THREAD

**Issue by linakherchi** [dongsoocha/mangomusic#3]
- [x] Contains correct datatypes
- [x] Contains appropriate constraints/details
    - [x] primary key
    - [x] not null
    - [x] unique
    - [x] indexed
    - [x] foreign key
- [x] Contains bullet points after the table that state which foreign keys will reference to which table, or references to the associations which will be made
  - [x] foreign key and table name are lowercased, snake_cased and `back_ticked`
- [x] Correctly formatted
    - [x] schema is written in a table format
    - [x] the table's name are lowercased, snake_cased and `back_ticked`
    - [x] the table header column names are bolded
    - [x] columns names are lowercased and snaked_cased and `back_ticked`

**Comment by linakherchi** [comment]
Thanks, Dongsoo ! 

What will a track number in your songs table save ?

**Comment by dongsoocha** [comment]
Hi Lina, 

Track number will reference which number it is on the album, so that on the albums page I can show the tracks in the album specified order!

**Comment by linakherchi** [comment]
Got it ! Thank you!

**Comment by linakherchi** [comment]
Needs playlists - Look at backend routes comment
