### ISSUE TITLE
State Shape

### ISSUE THREAD

**Issue by linakherchi** [dongsoocha/mangomusic#4]
- [x] State shape is flat!
- [x] State's keys are camelCased
- [x] All keys within the values in the state are accessible in the schema
- [x] Correctly formatted
    - [x] Sample state is rendered with triple backticks, and the language ` ```javascript...``` `). This will display the state as a code block instead of a giant line of text 
    - [x] Top level slices
        - [x] `entities`
        - [x] `session`
        - [x] `errors` (here or in `ui`)
        - [x] `ui` (if needed)
    - [x] Should NOT have nested slices, aka  `comments` inside of `posts`
      + Some info from other tables is ok, for instance:
        + the author username and imageurl for a post. basically any info that the user can't change
        + like count and a boolean on whether the user likes the post instead of a likes slice

**Comment by linakherchi** [comment]
Thanks, Dongsoo ! 

Make sure all of your snake case keys are camel cased.

**Comment by dongsoocha** [comment]
Okay, I have fixed the camel casing! Does the formatting also need some modifications?

Thanks!
Dongsoo

**Comment by linakherchi** [comment]
Thanks ! You're good

**Comment by linakherchi** [comment]
Needs playlists - Look at backend routes comment
