### ISSUE TITLE
Backend Routes

### ISSUE THREAD

**Issue by linakherchi** [dongsoocha/mangomusic#5]
- [x] Contains the following sections: HTML, API Endpoints(Backend)
- [x] Each route has a description
- [x] API Endpoint routes contains wildcard variables written in `snake_case`
- [x] Routes does not contain [superfluous routes](https://github.com/appacademy/curriculum/blob/master/rails/readings/routing-part-ii.md)
- [x] Have API routes that will allow the front end to get all info it needs and does not have unneeded routes:
    + probably doesn't need a `GET likes` api endpoint because that info comes through the post show

**Comment by linakherchi** [comment]
Thanks, Dongsoo ! 

I am not seeing routes related to playlists.
Also, please make sure to not nest your songs route. `/songs/:id` should be enough.

**Comment by dongsoocha** [comment]
Okay, I have modified the routes to include playlists and take out the nesting! 

Please let me know if anything else needs to be edited.

**Comment by linakherchi** [comment]
Hi Dongsoo ! 

I just realized you do not have a playlists table in your schema or in your state shape - You will need to add those accordingly if you are intending to have a playlists MVP.

Thanks

**Comment by linakherchi** [comment]
Thanks, Dongsoo ! 

What about adding and removing song from playlist ?
